### ISSUE TITLE
Do we need compression of output files?

### ISSUE THREAD

**Issue by jimgar** [smartdatafoundry/hive_guide#3]
Hey @mikerspencer 

I suspect we could do away with tarring and compression.

Currently the script `R/generate_test_data.R` ends with a call to `system()`. It compresses and tars the output files. In the readme we instruct users to `podman cp` this tarball out of the container and decompress locally using zstd.

If there is no compression the user can still get the files:

- Via container: Copy the directory of files out using `podman cp demo_data:data-output/test_data/ data-output/`
- Running locally: The files are output into `demo-data/test_data/` already

Benefits of removing:

- Fewer dependencies and breaking points, particularly around differences between OSes
- Shorter scripts
- Snappier instructions in the readme

Complexity we have to support/users have to do by keeping compression:

- tar comes in different versions, which is why @lawall4 gets an error (see https://github.com/smartdatafoundry/hive_guide/pull/1) when running `system(sprintf("tar -I 'zstd -T%s' -cvf data-output/test_data.tar.zst data-output/test_data", workers))`. It's because mac's tar does have the `-I` flag but it means something different to the Linux version
- It's a system dependency in the container
- zstd is a system dependency users have to install themselves
- Longer instructions in the readme

If you're happy to remove compression just say the word, and I can raise a small PR with the required changes.

**Comment by mikerspencer** [comment]
I think that's a really good catch. I'm happy for you to implement this.
